units:
  kx: U
  ky: U
  spacing: 0.5
  border: 5
points:
  key:
    padding: kx + spacing
    spread: kx + spacing
  zones:
    matrix:
      columns:
        outer:
          key.stagger: 0
          key.column_net: P106
        pinky:
          key.stagger: 0
          key.column_net: P104
        ring:
          key.stagger: 8
          key.column_net: P011
        middle:
          key.stagger: 5
          key.column_net: P006
        index:
          key.stagger: -5
          key.column_net: P008
        inner:
          key.stagger: -3
          key.column_net: P031
      rows:
        bottom:
          row_net: P100
        home:
          row_net: P024
        top:
          row_net: P022
        num:
          row_net: P020
outlines:
  left:
    - where: true
      what: rectangle
      size: [kx + border, ky + border]
      fillet: 2
pcbs:
  left:
    outlines:
      main:
        outline: left
    footprints:
      # MX Key switches
      keyswitches:
        where: /^matrix_(?!inner_top).*/
        what: mx
        params:
          hotswap: true
          keycaps: true
          from: "{{column_net}}"
          to: "{{colrow}}"
        adjust:
          rotate: -90
      keyswitch_rot:
        where: matrix_inner_top
        what: mx
        params:
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
        adjust:
          rotate: -180
      # Controller
      nice_nano:
        what: nice_nano
        params: 
          orientation: up
        where:
          ref: matrix_inner_num
          shift: [0.3, -5]
          rotate: -90
      # Diodes
      diode:
          what: diode
          where: /^matrix_(?!inner_top|inner_num).*/
          params: 
            from: "{{colrow}}"
            to: "{{row_net}}"
          adjust:
              shift: [-5, 0]
              rotate: 90
      diodes_controler_clearance:
          what: diode
          where: /^matrix_inner_(top|num).*/
          params: 
            from: "{{colrow}}"
            to: "{{row_net}}"
          adjust:
              shift: [-10, 0]
              rotate: 90
      # Battery jack
      jstph:
          what: jstph
          where:
            ref: matrix_middle_top
            shift: [-2, -10]
            rotate: -90
          params:
              side: B 
              pos: pos
              neg: GND
      # Reset switch 
      horizontal_reset:
        what: EVQPUC
        params:
          side: B
          from: GND
          to: RST
        where:
          ref: matrix_inner_top
          shift: [10, -19]
          rotate: -90
      # Power switch
      battery_switch:
        what: slider
        where:
          ref: matrix_inner_top
          shift: [9.8, -29]
          rotate: -90
        params:
          side: B
          from: pos
          to: RAW
