units:
  kx: u
  ky: u
  spacing: 0.0
  border: 5
  outline_measure: kx + border
points:
  key:
    padding: kx + spacing
    spread: ky + spacing
  zones:
    matrix:
      columns:
        ColA:
          key.stagger: 0
          key.column_net: P006
        ColB:
          key.stagger: 0
          key.column_net: P008
        ColC:
          key.stagger: 8
          key.column_net: P017
        ColD:
          key.stagger: 5
          key.column_net: P020
        ColE:
          key.stagger: -5
          key.column_net: P022
        ColF:
          key.stagger: -3
          key.column_net: P029
      rows:
        Row1:
          row_net: P011
        Row2:
          row_net: P009
        Row3:
          row_net: P100
    thumbs:
      anchor:
        ref: matrix_ColE_Row1
        shift: [-0.5kx, -1.25ky-spacing]
      columns:
        ColD:
          key.column_net: P020
        ColE:
          key:
            column_net: P022
            splay: -10
            shift: [3, -2]
        ColF:
          key:
            column_net: P029
            height: 1.5kx
            splay: -15
            shift: [8, 2]
      rows:
        Row0:
          row_net: P115     
outlines:
  left:
    - what: polygon
      operation: stack
      points: 
        - ref: matrix_ColA_Row1
          shift: [-0.5kx-border, -0.5ky-border]
        - ref: matrix_ColA_Row3
          shift: [-0.5kx-border, 0.5ky+border]
        - ref: matrix_ColB_Row3
          shift: [0.5kx-border+spacing, 0.5ky+border]
        - ref: matrix_ColC_Row3
          shift: [-0.5kx-border, 0.5ky+border]
        - ref: matrix_ColC_Row3
          shift: [0.5kx-border+spacing, 0.5ky+border]
        - ref: matrix_ColD_Row3
          shift: [-0.5kx-border, 0.5ky+border]
        - ref: matrix_ColD_Row3
          shift: [0.5kx+border+spacing, 0.5ky+border]
        - ref: matrix_ColE_Row3
          shift: [-0.5kx+border, 0.5ky+border]
        - ref: matrix_ColE_Row3
          shift: [1.5kx+border+spacing, 0.5ky+border]
        - ref: matrix_ColF_Row1
          shift: [0.5kx+border, -0.5ky+8]
        - ref: thumbs_ColF_Row0
          shift: [-0.5kx, 0.5ky+0.25ky+border]
        - ref: thumbs_ColF_Row0
          shift: [0.5kx+border, 0.5ky+0.25ky+border]
        - ref: thumbs_ColF_Row0
          shift: [0.5kx+border, -0.5ky-0.25ky-border]
        - ref: thumbs_ColF_Row0
          shift: [-0.5kx, -0.5ky-0.25ky-border]
        - ref: thumbs_ColE_Row0
          shift: [0,-0.5ky-border]
        - ref: thumbs_ColD_Row0
          shift: [-0.5kx-border,-0.5ky-border]
        - ref: matrix_ColA_Row1
          shift: [2.5kx+2*spacing+border-1, -0.5ky-border]
      fillet: 2
pcbs:
  left:
    outlines:
      main:
        outline: left
    footprints:
      # MX Key switches
      keyswitches:
        where: /^(matrix|thumb).*?(?<!ColF_Row2)$/
        what: mx
        params:
          hotswap: true
          keycaps: true
          from: "{{column_net}}"
          to: "{{colrow}}"
        adjust:
          rotate: -90
      keyswitch_rot:
        where: matrix_ColF_Row2
        what: mx
        params:
          hotswap: true
          keycaps: true
          from: "{{column_net}}"
          to: "{{colrow}}"
        adjust:
          rotate: -180
      # Controller
      nice_nano:
        what: nice_nano
        params: 
          orientation: up
        where:
          ref: matrix_ColF_Row3
          shift: [0.3, -2]
          rotate: -90
      # Diodes
      diode:
          what: diode
          where: /^(matrix|thumb).*?(?<!ColF_Row[23])$/
          params: 
            from: "{{colrow}}"
            to: "{{row_net}}"
          adjust:
              shift: [-8.5, -4.5]
              rotate: 90
      diode_ColF_Row2:
          what: diode
          where: matrix_ColF_Row2
          params: 
              from: "{{colrow}}"
              to: "{{row_net}}"
          adjust:
              shift: [-3.5, -8]
              rotate: 180
      diode_ColF_Row3:
          what: diode
          where: matrix_ColF_Row3
          params: 
              from: "{{colrow}}"
              to: "{{row_net}}"
          adjust:
              shift: [-3.5, -4]
              rotate: 90
      # Battery jack
      jstph:
          what: jstph
          where:
            ref: matrix_ColE_Row3
            shift: [-3, 6]
            rotate: -90
          params:
              side: B
              pos: pos
              neg: GND
      # Reset switch 
      horizontal_reset:
        what: EVQPUC
        params:
          side: F
          from: GND
          to: RST
        where:
          ref: matrix_ColF_Row3
          shift: [10, 15]
      # Power switch
      battery_switch:
        what: slider
        where:
          ref: matrix_ColE_Row3
          shift: [7.25, 13]
        params:
          side: B
          from: pos
          to: RAW
      front_text: &text
        what: text
        where: &textWhere
            ref: matrix_ColC_Row1
            shift: [0.75kx, -0.8ky]
        params: &textParams
            text: KiwiBoard\nRev1
            justify: right
            h_size: 3.0
            v_size: 3.0
            thickness: 0.4
